### ISSUE TITLE
Invalid value: ikev1

### ISSUE THREAD

**Issue by twlz0ne** [philpl/setup-strong-strongswan#10]
``` sh
============================================================
Starting up VPN...
============================================================

sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
ERROR: /etc/ipsec.conf: 26: keyword keyexchange, invalid value: ikev1
ERROR: /etc/ipsec.conf: 26: keyword keyexchange, invalid value: ikev1
ERROR: /etc/ipsec.conf: 26: keyword keyexchange, invalid value: ikev1
unknown stack
Redirecting to: start ipsec
start: Job failed to start
```

``` sh
root@vps:~# sed -n 26p /etc/ipsec.conf
  keyexchange=ikev1

root@vps:~# uname -a
Linux 3.16.0-50-generic #67~14.04.1-Ubuntu SMP Fri Oct 2 22:07:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by philpl** [comment]
@twlz0ne Sorry, for replying this late. I will try to reproduce this as soon as I've got time

**Comment by cmendes0101** [comment]
I'm also getting this

ERROR: /etc/ipsec.conf: 26: keyword keyexchange, invalid value: ikev1
ERROR: /etc/ipsec.conf: 26: keyword keyexchange, invalid value: ikev1
unknown stack
Redirecting to: start ipsec
start: Job failed to start


Linux admin 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Pablohn26** [comment]
Same problem here. 

>Fedora 24  Linux  4.6.7-300.fc24.x86_64 #1 SMP Wed Aug 17 18:48:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

> Linux strongSwan U5.4.0/K4.6.7-300.fc24.x86_64

**Comment by xiaoronglv** [comment]
============================================================
Applying changes...
============================================================


============================================================
Create /etc/init.d/vpn-assist helper...
============================================================


============================================================
Starting up VPN...
============================================================

ERROR: /etc/ipsec.conf: 26: keyword keyexchange, invalid value: ikev1
ERROR: /etc/ipsec.conf: 26: keyword keyexchange, invalid value: ikev1
ERROR: /etc/ipsec.conf: 26: keyword keyexchange, invalid value: ikev1
unknown stack
Redirecting to: start ipsec
start: Job is already running: ipsec


same problem.

**Comment by 275287902** [comment]
```
ubuntu@ip-172-31-20-169:~$ sudo /etc/init.d/vpn-assist start
ERROR: /etc/ipsec.conf: 26: keyword keyexchange, invalid value: ikev1
ERROR: /etc/ipsec.conf: 26: keyword keyexchange, invalid value: ikev1
ERROR: /etc/ipsec.conf: 26: keyword keyexchange, invalid value: ikev1
unknown stack 
Redirecting to: start ipsec
start: Job failed to start
```
same problem.

**Comment by Conver** [comment]
Same.

**Comment by mask8** [comment]
Make sure that you don't have any other version of strongswan or openswan installed in /usr/local/bin/ or any other paths.

You can run `which ipsec` command and make sure its executable's location is /usr/sbin/ipsec. If not, edit /etc/init.d/vpn-assist script and change "ipsec" to "/usr/sbin/ipsec" to call right ipsec command of StrongSwan. I hope this tip helps

**Comment by cmendes0101** [comment]
That was my issue, its working now. @mask8 thanks

**Comment by harisphnx** [comment]
Any updates on this? I am facing the same problem.

**Comment by philpl** [comment]
@harisphnx @twlz0ne @Conver @mask8 @275287902 Are you guys sure that this is happening with Strongswan? Can one of you check which `ipsec` it's using? If it's a matter of not using the Strongswan `ipsec`, I might have to put a safeguard into the setup script.

**Comment by mask8** [comment]
like I mentioned, I had /usr/local/sbin/ipsec installed(not sure if it was different strongswan or openswan) so that was conflicting to the /usr/sbin/ipsec that this setup had me install.

**Comment by philpl** [comment]
@mask8 In that case I'll close this in favour of #36
