### ISSUE TITLE
Stuck at Installing necessary dependencies

### ISSUE THREAD

**Issue by nightkidssh** [philpl/setup-strong-strongswan#11]
The script stuck at 
Installing necessary dependencies

**Comment by HappyLoaf** [comment]
Suspect it's because it's not calling pacapt -Sy

    happyloaf@StrongSwan-VPNGW:~$ sudo /tmp/strongswan/pacapt -S make g++ gcc libgmp-dev iptables xl2tpd libssl-dev
Reading package lists... Done

So "pacapt" is sat around waiting for input

**Comment by anaggh** [comment]
+1 Script hung at the same state.

**Comment by rained23** [comment]
adding --noconfirm after pacapt -S on line 177 might solve the problems.

**Comment by philpl** [comment]
(sorry for responding this late)

@rained23 That looks right, I will test this as soon as I've got time. thx for reporting

**Comment by schnaidar** [comment]
An ugly workaround that worked for me: manually installing the depenencies
`apt-get install make g++ gcc libgmp-dev iptables xl2tpd libssl-dev`

**Comment by cind3r** [comment]
@rained23 This seems to have worked for me. Thanks!

**Comment by philpl** [comment]
Fixed in 896e7f0
