### ISSUE TITLE
Not working on Ubuntu

### ISSUE THREAD

**Issue by xiti** [philpl/setup-strong-strongswan#16]
Hi, 

I tried your script on a Ubuntu box. Not working...

root@ubt:~# curl -L -O https://raw.github.com/philplckthun/setup-strong-strongswan/master/setup.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 10860  100 10860    0     0   4183      0  0:00:02  0:00:02 --:--:-- 73378
root@ubt:~# sudo ./setup.sh
**sudo: ./setup.sh: command not found**

**Comment by roederw** [comment]
You have to change the permissions of setup.sh. Run chmod +x setup.sh and then run the sudo command.
