### ISSUE TITLE
VPN Account Tool

### ISSUE THREAD

**Issue by zackdevine** [philpl/setup-strong-strongswan#19]
I have created a simple to use tool to easily add VPN accounts to both `/etc/ipsec.secrets` and `/etc/ppp/chap-secrets`. It is adapted from your setup script, and I hope it is helpful for some server administrators looking for an easy way to add additional users to the StrongSwan VPN!

[You can find it here](https://github.com/zackdevine/setup-strongswan-vpn-account)

**Comment by LBYPatrick** [comment]
Can you gitpush your code? Thanks!!!
