### ISSUE TITLE
no outcoming traffic and couldn't connect with winXP

### ISSUE THREAD

**Issue by DrDaveone** [philpl/setup-strong-strongswan#21]
1)Server: BananaPi M1 (bananian 1604), connection by ethernet to router
Client: Xiaomi Redmi Note 4g Single Sim (4.4.4, miui 7.3.1.0 KHIMIDD, Kernel 3.4.0)
in another place incoming speed is max as possible (avr. 2000kBps), but outcoming speed --> 0kbps, whereupon can't use vpn at all.

2)i can't connect with windows xp

**Comment by philpl** [comment]
I can't really debug this as I do not have the proper testing for different environments in place. Sorry!
