### ISSUE TITLE
"no private key found" when connecting with iOS IKEv2

### ISSUE THREAD

**Issue by keisisqrl** [philpl/setup-strong-strongswan#26]
When trying to connect using an IKEv2 client on iOS, the following error is thrown:

Sep  5 23:31:04 digitalocean charon: 01[IKE] no private key found for '159.203.228.129'

iOS requires an ID for the server, but this script doesn't seem to generate any private keys so the deployed server won't talk to it.

**Comment by philpl** [comment]
You'll have to generate them yourself. This script doesn't provide RSA authentication sadly.

**Comment by keisisqrl** [comment]
Okay, thank you.
