### ISSUE TITLE
IPTables rule affects MySQL connections

### ISSUE THREAD

**Issue by leeci** [philpl/setup-strong-strongswan#29]
Environment : Ubuntu 16.04.1
I host a minecraft server and use the script in same machine.
When I trying to start MC server, all of plugin can't create a MySQL connection.
Here is the error message:  [pastebin](http://pastebin.com/vz6zyaH2)
To fix this issue, need to modify iptables' rule:
`sudo iptables --table nat --append POSTROUTING -o ppp0 --jump MASQUERADE`
I have no sense but it is working. Hope to fixed it correctly.

**Comment by philpl** [comment]
Hm, that's weird. The iptable-rule should apply to all interfaces. Do you have an idea why it's not affecting / adversely affecting ppp0?

https://github.com/philpl/setup-strong-strongswan/blob/master/setup.sh#L428

**Comment by fulldecent** [comment]
Recommending to close an unresponsive reporter

**Comment by leeci** [comment]
This issue has been solved. Just share my experience.
OK, I close it by myself.
