### ISSUE TITLE
charon refused to be started

### ISSUE THREAD

**Issue by maciekish** [philpl/setup-strong-strongswan#30]
Hi,
I just ran the script but it doesnt seem to be working. xl2tpd is listening on 1701 but that's it. The system reports that the strongswan starter is running but there are errors in the log:

	root@localhost:~# service strongswan status -l
	● strongswan.service - strongSwan IPsec IKEv1/IKEv2 daemon using ipsec.conf
	   Loaded: loaded (/lib/systemd/system/strongswan.service; enabled; vendor preset: enabled)
	   Active: active (running) since Mon 2016-11-21 16:09:41 UTC; 1min 55s ago
	 Main PID: 25836 (starter)
	   CGroup: /system.slice/strongswan.service
	           └─25836 /usr/libexec/ipsec/starter --daemon charon --nofork

	Nov 21 16:11:31 localhost.localdomain charon[29833]: 00[CFG]   loaded IKE secret for %any
	Nov 21 16:11:31 localhost.localdomain charon[29833]: 00[CFG]   loaded EAP secret for ma*****sh
	Nov 21 16:11:31 localhost.localdomain charon[29833]: 00[CFG]   loaded EAP secret for ma*****sh
	Nov 21 16:11:31 localhost.localdomain charon[29833]: 00[CFG] loaded 0 RADIUS server configurations
	Nov 21 16:11:31 localhost.localdomain charon[29833]: 00[LIB] failed to load 1 critical plugin feature
	Nov 21 16:11:31 localhost.localdomain charon[29833]: 00[DMN] initialization failed - aborting charon
	Nov 21 16:11:32 localhost.localdomain ipsec[25836]: charon has died -- restart scheduled (5sec)
	Nov 21 16:11:32 localhost.localdomain ipsec[25836]: charon refused to be started
	Nov 21 16:11:32 localhost.localdomain ipsec_starter[25836]: charon has died -- restart scheduled (5sec)
	Nov 21 16:11:32 localhost.localdomain ipsec_starter[25836]: charon refused to be started

**Comment by philpl** [comment]
Can you acquire more verbose logs? Otherwise this is not actually giving me the reason as to why it died
