### ISSUE TITLE
work with iphone but not win7 or win10

### ISSUE THREAD

**Issue by secretwhy** [philpl/setup-strong-strongswan#31]
this works perfectly on iphone.
but i can‘t set up the connection on windows7 or windows 10 device.

**Comment by freeyoung** [comment]
@secretwhy Do you have the same issue as https://github.com/philpl/setup-strong-strongswan/issues/12? Could you please post your server logs here?

**Comment by secretwhy** [comment]
[error log.txt](https://github.com/philpl/setup-strong-strongswan/files/630483/error.log.txt)

Hey. Thanks for looking into this.
I am using an Alibaba server in Singapore. Operation System is Ubuntu 14.04 64bit. This was freshly installed system. I didn't make any chage to it except running your script.

The client machine is running a freshly installed windows 10 64bit system. I can connect vpn service with other server using PPTP protacol.

**Comment by freeyoung** [comment]
@secretwhy The client log doesn't help much. What I asked for was the server log.
I assume you are using an Aliyun VM with the VPC network, which for some reasons doesn't work with L2TP. Probably you can create a VM with the classic network and give it a try.

**Comment by secretwhy** [comment]
Sorry but I don't know how to get a server log. But again it is working fine with my iPhone. So it is not a problem with aliyun server?

**Comment by freeyoung** [comment]
@secretwhy It is. But you have to use the "classic" network instead of "VPC".

**Comment by secretwhy** [comment]
Hi. I just checked. My ECS is using classic network.

**Comment by freeyoung** [comment]
@secretwhy Then I don't know...unless you can post your server logs here. Windows is special.

**Comment by secretwhy** [comment]
Hi Eric, is it possible for you to log on my server and have a look? If yes, how can I send you the ip and pwd?

**Comment by secretwhy** [comment]
Hey. This problem is solved. Pls refer to below link.
http://www.cnblogs.com/hjklin/p/5877197.html
And do not use google's DNS server 8.8.8.8, othewise cannot set up vpn connection either.

**Comment by freeyoung** [comment]
@secretwhy So your issue was actually resolved by setting `AssumeUDPEncapsulationContextOnSendRule` to `dword:00000002`?

Also 8.8.8.8 shouldn't have caused connection failures...weird.

**Comment by secretwhy** [comment]
Yes. The issue was solved but adding this value. And you are right, it is
irrelevant about the google dns.
But have 2 new problems:
1. If the server reboot, the VPN service won't run automatically. Because I
don't know anything about how to restart the service so I run your script
again and it works.
2. I can connect the VPN but still I can't visit google or facebook and
etc. Other Chinese website is OK. I guess this is DNS pollution but I can't
find a solution so far.

Eric Qian <notifications@github.com>于2016年12月5日 周一下午10:47写道：

**Comment by freeyoung** [comment]
1. `update-rc.d vpn-assist defaults`

2. You have to push google public dns or opendns servers from the server side, or you configure them client side.

**Comment by secretwhy** [comment]
1. Thank you kindly.
2. The problem was caused by DNS pollution. (GFW). I am using dnscrypt from opendns now and the problem is solved.

**Comment by freeyoung** [comment]
@secretwhy Awesome. Glad it works for you now!

**Comment by philpl** [comment]
Glad to see that this works for you. I'm going to close this issue :)

@secretwhy @freeyoung Are you interested in writing up some Wiki pages or a PR for the Readme?

**Comment by fulldecent** [comment]
@secretwhy @freeyoung can you please assist in documenting this in a Wiki page here. 

Documentation in Chinese will be helpful if that is easier for you.
