### ISSUE TITLE
error: OpenSSL libcrypto not found

### ISSUE THREAD

**Issue by fulldecent** [philpl/setup-strong-strongswan#33]
...
checking x86/x64 target... yes
checking for main in -lcrypto... no
configure: error: OpenSSL libcrypto not found

============================================================
An unexpected error occured!
============================================================

**Comment by philpl** [comment]
Does it work with this PR merged? https://github.com/philpl/setup-strong-strongswan/pull/25

**Comment by fulldecent** [comment]
Yes, fixed now

**Comment by ysaotome** [comment]
for Unbutu 16.10
```
apt-get install libssl-dev
```
