### ISSUE TITLE
Error no xl2tpd

### ISSUE THREAD

**Issue by fulldecent** [philpl/setup-strong-strongswan#34]
This is how I solved it on CentOS:

```
wget http://mirror.nl.leaseweb.net/epel/6/i386/epel-release-6-8.noarch.rpm
rpm -ivh ./epel-release-6-8.noarch.rpm
yum install xl2tpd
```

**Comment by philpl** [comment]
Do you know why the installation isn't actually installing this package?

https://github.com/philpl/setup-strong-strongswan/blob/master/setup.sh#L205

**Comment by fulldecent** [comment]
Possibly because of this line rpm -ivh ./epel-release-6-8.noarch.rpm

Perhaps a problem with pacapt or maybe we are missing a configuration option.

**Comment by philpl** [comment]
@fulldecent It's possible that `pacapt` was broken, and unfortunately just downloading their latest script from their `ng` branch is the recommended installation. Therefore I don't even have trust downloading their latest release, which might just as well break at some point.

I'll close this for now and assume that it is / was a problem with `pacapt`.
