### ISSUE TITLE
Full instructions for OpenVZ

### ISSUE THREAD

**Issue by fulldecent** [philpl/setup-strong-strongswan#35]
Note:

To make this work on OpenVZ with TUN enabled on buyvm.net servers running CentOS 6, I did the following:

 1. Use this fork of setup-strong-strongswan https://github.com/philpl/setup-strong-strongswan/pull/25
 2. `chkconfig vpn-assist on`
 3. Set up IPtables

    iptables -A INPUT -p esp -j ACCEPT
    iptables -A INPUT -p udp --dport 500 -j ACCEPT
    iptables -A INPUT -p udp --dport 4500 -j ACCEPT
    iptables -A POSTROUTING -t nat -s 10.0.0.0/8 -j SNAT --to-source YOURSERVERIP_GOES_HERE
    service iptables save 

4. Run `service vpn-assist start`

**Comment by philpl** [comment]
@fulldecent Are you interested in adding this to the wiki as a page?

**Comment by fulldecent** [comment]
Created

**Comment by philpl** [comment]
@fulldecent Cheers!
