### ISSUE TITLE
l2tp denied connection to unauthorized peer

### ISSUE THREAD

**Issue by singit** [philpl/setup-strong-strongswan#6]
Here, set /etc/xl2tpd/xl2tpd.conf: 
require authentication = no
may solve the problem.

otherwise, you cannot connect to the server by default setup.

**Comment by philplckthun** [comment]
I'm thinking whether I've configured the IPSec over L2TP to use xl2tpd's auth system or strongswan's. I'll have to test changing the config to authentication=no I guess

**Comment by IsaiahJTurner** [comment]
Thank you for this! I could not connect but setting `require authentication = no` fixed it.

**Comment by IsaiahJTurner** [comment]
Does this open security vulnerabilities?

**Comment by lovemyliwu** [comment]
thank you @singit solved the l2pt connection issue. now l2tp and ipsec both work correct.
