### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gaiterjones** [philpl/setup-strong-strongswan#9]
I installed this on a new 64 bit amazon EC2 server, installation seems to go ok, but I can't connect any clients. Also trying to uninstall I downloaded the source as suggested but there is no rule to make target `uninstall'. Any ideas where I am going wrong.

**Comment by philpl** [comment]
This is very unspecific. As long as there are no specifications and logs to the installation process, the machine itself and your client including any configuration, I can't help you

**Comment by gaiterjones** [comment]
Yes I know it's unspecific, but your script is an all in one installer, designed to make the VPN setup simple. New AWS instance, script ran without errors, client configured. Didn't work.  Similarly uninstall didn't work. You can close this issue, I guess it was more of a frustrated comment than a problem. I have used another VPN install.
